### PR TITLE
Add --display option

### PR DESCRIPTION
**Pull request by shihanng**
Hi, I wonder if you would accept this PR:

gpg-agent might call pinentry-program with additional argument:

```
--display /private/tmp/com.apple.launchd.weZyuRW3RM/org.macosforge.xquartz:0
```

Since bitwarden-pinentry does not recognized and parse this `--display` argument, the program will panic due to the unknown argument error.

This approach adds the `--display` argument into bitwarden-pinentry to mitigate the panic but ignore the value of that argument.

go-arg is chosen as the argument/flag parser instead of the Go's stdlib Flag package to handle the double dashes (`--`) arguments implementation as oppose to the default single dash. This also causes breaking change as the config argument has to be called as `--config` instead of `-config`.

Let me know what you think. Thanks!

### CODE REVIEW

**Comment by mrahbar** [comment]
What is the purpose of `--display`? Do you actually need it or only want that bitwarden-pinentry won't crash? Dealing with unknown flags seems to me a better approach at the current state. What do you think?

**Comment by shihanng** [comment]
> What is the purpose of --display?

According to the manual of [gpg-agent](https://linux.die.net/man/1/gpg-agent) and manual [pinentry-gnome3](http://manpages.ubuntu.com/manpages/bionic/man1/pinentry-gnome3.1.html) (as reference), it is for "localization information".

> Do you actually need it or only want that bitwarden-pinentry won't crash? 

I don't actually need it. Just want that bitwarden-pinentry won't crash when receiving this argument. At least on my macOS environment, it seems that I can't tell `gpg-agent` to call `bitwarden-pinentry` without the `--display` argument. Maybe I am missing something? :thinking:

**Comment by mrahbar** [comment]
Do you mind changing this PR to make bitwarden-pinentry not to fail if it gets called with unknown flags. I think this would be a better solution since the additional flags are not needed.

**Comment by shihanng** [comment]
Sorry for the late reply :pray:. I will try to create another PR in the future for this. Thank you for your feedback :heart:

**Pull request closed without merging**
